function [] = fcnCREATEWAKE(matNEWWAKE)


[ vecDVEHVSPN, vecDVEHVCRD, ...
    vecDVEROLL, vecDVEPITCH, vecDVEYAW,...
    vecDVELESWP, vecDVEMCSWP, vecDVETESWP, ...
    vecDVEAREA, matDVENORM, ...
    matVLST, matDVE ] = fcnDVECORNER2PARAM( matCENTER, P1, P2, P3, P4 )


end

