function [fitresult, gof] = fcnLINSPLINE(XDATA, YDATA)
%CREATEFIT(XDATA,YDATA)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : XDATA
%      Y Output: YDATA
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 11-Dec-2018 17:49:29


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( XDATA, YDATA );

% Set up fittype and options.
ft = 'linearinterp';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, 'Normalize', 'on' );


