function [SURF, INPU, COND, MISC, VISC, OUTP, valGUSTTIME, n] = fcnMOVESTRUCTURE(INPU, VEHI, MISC, COND, SURF, VISC, FLAG, OUTP, valGUSTTIME, valTIMESTEP, n)

if valTIMESTEP <= COND.valSTIFFSTEPS || FLAG.STIFFWING == 1

    [SURF, INPU, MISC, VISC, OUTP] = fcnSTIFFWING(INPU, VEHI, MISC, COND, SURF, VISC, FLAG, OUTP, valTIMESTEP);

    if FLAG.STIFFWING == 2
        [INPU, SURF] = fcnSTRUCTDIST(INPU, SURF);
    end

elseif valTIMESTEP == n*COND.valSTIFFSTEPS + 1 || valGUSTTIME > 1
    [COND, INPU, OUTP, MISC, SURF, valGUSTTIME] = fcnFLEXWING(INPU, COND, SURF, OUTP, FLAG, MISC, valGUSTTIME, valTIMESTEP);
    n = n + 1;
else
    [SURF, INPU, MISC, VISC, OUTP] = fcnSTIFFWING_STATIC(INPU, VEHI, MISC, COND, SURF, VISC, OUTP, valTIMESTEP);
end

[SURF] = fcnWINGSTRUCTGEOM(SURF, INPU); 