function [SURF, INPU, COND, MISC, VISC, OUTP, FLAG, TRIM, VEHI, n] = fcnMOVESTRUCTURE(INPU, VEHI, MISC, COND, SURF, VISC, FLAG, OUTP, TRIM, valTIMESTEP, n)

if (valTIMESTEP <= COND.valSTIFFSTEPS && FLAG.FLIGHTDYN == 0) || FLAG.STIFFWING == 1 || (FLAG.FLIGHTDYN == 1 && valTIMESTEP <= COND.valSTIFFSTEPS)

    [SURF, INPU, MISC, VISC, OUTP, VEHI] = fcnSTIFFWING(INPU, VEHI, MISC, COND, SURF, VISC, FLAG, OUTP, valTIMESTEP);

elseif valTIMESTEP >= COND.valSTIFFSTEPS + 1
    
    [COND, INPU, OUTP, MISC, SURF, FLAG, TRIM, VEHI] = fcnFLEXVEHI(INPU, COND, SURF, OUTP, FLAG, MISC, VEHI, TRIM, valTIMESTEP);
    n = n + 1;
    
% elseif FLAG.FLIGHTDYN == 1 && valTIMESTEP >= 30
% 
%     SURF.matCENTER_old = SURF.matCENTER;
%     [SURF, MISC, COND, INPU] = fcnMOVEVEHI(COND, SURF, OUTP, INPU, MISC, FLAG, VEHI, TRIM);
%     [SURF.matUINF] = fcnFLEXUINF(SURF.matCENTER_old, SURF.matCENTER, COND.valDELTIME, 1);
    
else
    
    [SURF, INPU, MISC, VISC, OUTP] = fcnSTIFFWING_STATIC(INPU, VEHI, MISC, COND, SURF, VISC, OUTP, valTIMESTEP);
    
end