function [hLogo] = fcnPLOTLOGO(vtexttop, vtextleft, vtextsize, vcolor, vbackground)


vmargin = 5/14*vtextsize;
vlinewidth = 0.75/14*vtextsize;

RAALF = sprintf('RYERSON\nAPPLIED\nAERODYNAMICS\nLABORATORY OF\nFLIGHT');

hLogo = annotation('textbox','Position',[vtextleft vtexttop 0.0001 0.0001],...
    'string',RAALF,'HorizontalAlignment','left',...
    'FontSize',vtextsize,...
    'FontName','Agency FB',...
    'VerticalAlignment','top',...
    'Color',vcolor,...
    'BackgroundColor',vbackground,...
    'EdgeColor',vcolor,...
    'LineWidth',vlinewidth,...
    'Margin',vmargin,'Units','points',...
    'FitBoxToText','on');


end