clc
clear

filename = 'inputs/XMLtest.vap';


[matGEOM, valMAXTIME, valMINTIME, valDELTIME, valDELTAE, valDENSITY, valKINV, valVEHICLES, ...
    matVEHORIG, vecVEHVINF, vecVEHALPHA, vecVEHBETA, vecVEHROLL, vecVEHPITCH, vecVEHYAW, ...
    vecWINGS, vecWINGINCID, vecWINGAREA, vecWINGSPAN, vecWINGCMAC, vecWINGM, vecPANELS, ...
    vecSYM, vecN, vecM, vecSECTIONS, matSECTIONS, vecSECTIONPANEL, vecWING, vecWINGVEHICLE, valPANELS...
    ] = fcnXMLREAD(filename);

[matCENTER0, vecDVEHVSPN, vecDVEHVCRD, vecDVELESWP, vecDVEMCSWP, vecDVETESWP, ...
    vecDVEROLL, vecDVEPITCH, vecDVEYAW, vecDVEAREA, matDVENORM, ...
    matVLST0, matNPVLST0, matDVE, valNELE, matADJE, ...
    vecDVESYM, vecDVETIP, vecDVEWING, vecDVELE, vecDVETE, vecDVEPANEL] = fcnGENERATEDVES(valPANELS, matGEOM, vecSYM, vecN, vecM);

% matGEOM - 2x5xvalPANELS matrix of [x y z chord twist]

